import type { Metadata } from "next";
import { LayoutSetter } from "@/components/layouts/layout-setter";
import { CoinBar } from "@/components/layouts/coin-bar";

export const metadata: Metadata = {
    title: "Genekriti",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <LayoutSetter coinChildren={<CoinBar />}>
            {children}{" "}
        </LayoutSetter>
    );
}
