export const serviceMessages = {
  EVENT_FOUND: "Event successfully found by Id",
  EVENT_NOT_FOUND: "Event not found",
  EVENT_UPDATE_SUCCESS: "Event updated successfully",
  EVENT_UPDATE_FAILURE: "Event not updated",
  EVENT_FOUND_ALL: "All events found successfully",
  EVENT_DELETE_SUCCESS: "Event delete successfully",
  EVENT_DELETE_FAILURE: "Event not deleted",
  EVENTS_FOUND_SUCCESS: "Events found successfully",
  EVENT_COMPLETE_SUCCESS: "Event marked as completed successfully",
  EVENT_COMPLETE_FAILURE: "Event could not be marked as completed",
  EVENT_REGISTRATION_SUCCESS: "Registered to event successfully",
  EVENT_REGISTRATION_FAILURE: "Oops, Error registering to the event",
  EVENT_REGISTRANTS_FETCH_SUCCESS: "Registrants fetched successfully",
  EVENT_REGISTRANTS_FETCH_FAILURE:
    "Oops, Error fetching registrants of the event",
  EVENT_REGISTRANT_FOUND: "Registrant found successfully",
  EVENT_REGISTRANT_NOT_FOUND: "Oops, registrant not found",
  EVENT_ATTENDEE_MARKED_SUCCESS: "Marked as attendee successfully",
  EVENT_ATTENDEE_MARKED_FAILURE: "Oops, some error marking your attendance",
  EVENT_ORGANIZTION_FOUND: "Event organizer found successfully",
  EVENT_ORGANIZTION_NOT_FOUND: "Oops, event organizer not found",
  VIDEO_CREATE_SUCCESS: "Video uploaded successfully",
  VIDEO_UPLOAD_FAILURE: "Oops, some error while uploading the video",
  VIDEO_FOUND: "Video fetched successfully",
  VIDEO_NOT_FOUND: "Video found successfully",
  VIDEO_UPDATE_SUCCESS: "Video updated successfully",
  VIDEO_UPDATE_FAILURE: "Oops, Video could not be uploaded",
  VIDEO_DELETE_SUCCESS: "Video deleted successfully",
  VIDEO_DELETE_FAILURE: "Oops, Vidoe could not be deleted",
  COMMENT_CREATED_SUCCESS: "Comment created successfully",
  COMMENT_CREATED_FAILURE: "Oops, comment could not be created",
  COMMENT_UPDATE_SUCCESS: "Comment updated successfully",
  COMMENT_UPDATE_FAILURE: "Oops, comment could not be updated",
  COMMENT_DELETE_SUCCESS: "Comment deleted successfully",
  COMMENT_DELETE_FAILURE: "Oops, comment could not be deleted",
  COMMENTOR_FOUND_SUCCESS: "Commentor found successfully",
  COMMENTOR_NOT_FOUND: "Oops, commentor not found",
  PRODUCT_PUBLISH_SUCCESS: "Product published successfully",
  PRODUCT_PUBLISH_FAILURE: "Oops, product could not be published",
  CONVERSATION_ADD_SUCCESS: "Conversation added succesfully",
  CONVERSATOIN_ADD_FAILURE: "Oops, conversation could not be added",
  CONVERSATION_FETCH_SUCCESS: "Converstation fetched successfully",
  CONVERSATION_FETCH_FAILURE: "Oops, converstation could not be fetched",
};
